### PR TITLE
fix: Sri Lanka NIC number validation

### PR DESCRIPTION
**Pull request by rajithaeyee**
added Sri Lanka NIC number validation feature

### CODE REVIEW

**Review by koblas — COMMENTED** [review]
Great!  Can we get the test failure fixed.

**Comment by rajithaeyee** [comment]
@koblas test failures are not occured Sri Lankan NIC but **from bis.spec.ts(Belgian)  and curp.spec.ts (Mexico)**,  I will go through the code and see what's happening there. Thanks!

**Comment by koblas** [comment]
@rajithaeyee Found the issue, a bug in a unit test (padding issue) committing the fix shortly so you can rebase.

**Comment by rajithaeyee** [comment]
done @koblas

**Pull request merged**
